### PR TITLE
Avoid repeated calls to MPI_Comm_size

### PR DESCRIPTION
**Pull request by yieldthought**
When using net::MpiCommunicator, net.Size() is implemented by a call to MPI_Comm_size. Using it as the upper bound in this loop actually caused it to dominate the time spent in the RequestComms phase. I noticed this reviewing some old MAP files from the ARCHER work - at 8k cores this actually consumed 12% of wall-clock time during the RunSimulation() phase. At 16k cores it took 45% of the time. This was for very short iteration timesteps but considering the simplicity of the fix and the apparent O(N^2) in #procs it'll probably manifest in production scale runs sooner or later as we continue to reach for higher scales.

### CODE REVIEW

**Comment by rupertnash** [comment]
Hi - thanks for the report and fix.
We're actually preparing to make another public release in the next week or two so we will check this out.

Who are you by the way?

Thanks

**Comment by yieldthought** [comment]
Thanks Rupert. I'm Mark O'Connor from Allinea Software, we worked with you on this in 2014 (http://www.cray.com/sites/default/files/resources/Case-Study-Allinea-Brain-Surgery.pdf) and are the WP4 leaders for the H2020 ComPat project with UCL.

**Comment by rupertnash** [comment]
Hi Mark, can you please rebase this commit onto the HEAD of master?

**Comment by mobernabeu** [comment]
Thanks a lot for your contribution @yieldthought.

I have cherry picked your commit 6070a20 into our development repository. The commit will appear in HemeLB's public repo (UCL/hemelb) next time we push the development repo to it.

**Pull request closed without merging**
